


# Selection Categories for charts

tax_system = c("Future of Consumption",
															"Future of Digital Economy and Society",
															"Future of Economic Growth and Social Inclusion",
															"Future of Education, Gender and Work",
															"Future of Energy",
															"Future of Environment and Natural Resource Security",
															"Future of Financial and Monetary Systems",
															"Future of Food Security and Agriculture",
															"Future of Health and Healthcare",
															"Future of Information and Entertainment",
															"Future of International Trade and Investment",
															"Future of Long-Term Investing, Infrastructure and Development",
															"Future of Mobility",
															"Future of Production")

tax_eco = c("Africa",
												"Nigeria",
												"South Africa",
												"ASEAN",
												"Indonesia",
												"Philippines",
												"Republic of Korea",
												"China",
												"Russian Federation",
												"Ukraine",
												"European Union",
												"Germany",
												"Turkey",
												"United Kingdom",
												"India",
												"Pakistan",
												"Japan",
												"Argentina",
												"Brazil",
												"Colombia",
												"Latin America",
												"Mexico",
												"Jordan",
												"Middle East and North Africa",
												"United Arab Emirates",
												"Canada",
												"United States")

tax_ind = c("Chemistry and Materials Industry",
												"Electricity",
												"Mining and Metals",
												"Oil and Gas",
												"Agriculture, Food and Beverage",
												"Retail, Consumer Goods and Lifestyle",
												"Banking and Capital Markets",
												"Insurance and Asset Management",
												"Engineering and Construction",
												"Real Estate",
												"Institutional Investors",
												"Private Investors",
												"Healthcare Delivery Systems",
												"Electronics",
												"Information Technology",
												"Telecommunications",
												"Media, Entertainment and Information",
												"Automotive",
												"Aviation and Travel",
												"Supply Chain and Transportation")

tax_glob = c("Blockchain",
													"Cities and Urbanization",
													"Competitiveness Framework",
													"Emerging Multinationals",
													"Family Businesses",
													"Future of Enterprise",
													"Inclusive Growth Framework",
													"Innovation",
													"Migration",
													"Public Finance and Social Protection Systems",
													"Sustainable Development",
													"Workforce and Employment",
													"Circular Economy",
													"Climate Change",
													"Decarbonizing Energy",
													"Forestry",
													"Oceans",
													"Water",
													"3D Printing",
													"Advanced Materials",
													"Artificial Intelligence and Robotics",
													"Biotechnology",
													"Blockchain",
													"Human Enhancement",
													"Future of Manufacturing",
													"Neuroscience",
													"Sensors",
													"Space",
													"Virtual and Augmented Reality",
													"Arctic",
													"Corruption",
													"Cybersecurity",
													"Geo-economics",
													"Global Governance",
													"Human Rights",
													"Humanitarian Response",
													"Illicit Economy",
													"International Security",
													"Internet Governance",
													"Justice",
													"Nuclear Security",
													"Risk and Resilience",
													"Ageing",
													"Arts and Culture",
													"Behaviour Change",
													"Civic Participation",
													"Demographic Dividend",
													"Education and Skills",
													"Entrepreneurship",
													"Fourth Industrial Revolution",
													"Future of Government",
													"Gender Parity",
													"Global Health",
													"Infrastructure",
													"Mental Health",
													"Role of Faith",
													"Social Innovation",
													"Social Media",
													"Values")


sel_dis <- c("Statistics","Strength Analysis","2nd order Loops")
sel_cat <- c("All Insights","Economies","Global Issues","Industries","System Initiatives")

ins_eco <- tax_eco; ins_eco <- sort(ins_eco)
ins_glo <- tax_glob; ins_glo <- sort(ins_glo)
ins_ind <- tax_ind; ins_ind <- sort(ins_ind)
ins_sys <- tax_system; ins_sys <- sort(ins_sys)
ins_all <- c(ins_eco,ins_glo,ins_ind,ins_sys); ins_all <- sort(ins_all)